/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_node = 2,
  anon_sym_COLON = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_edge = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_QMARK = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_enum = 11,
  anon_sym_LPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_RPAREN = 14,
  anon_sym_Vector = 15,
  anon_sym_String = 16,
  anon_sym_Bool = 17,
  anon_sym_I32 = 18,
  anon_sym_I64 = 19,
  anon_sym_U32 = 20,
  anon_sym_U64 = 21,
  anon_sym_F32 = 22,
  anon_sym_F64 = 23,
  anon_sym_DateTime = 24,
  anon_sym_Date = 25,
  anon_sym_AT = 26,
  sym_type_name = 27,
  sym_enum_value = 28,
  sym_string = 29,
  sym_float = 30,
  sym_integer = 31,
  anon_sym_true = 32,
  anon_sym_false = 33,
  sym_line_comment = 34,
  sym_block_comment = 35,
  sym_source_file = 36,
  sym_node_decl = 37,
  sym_edge_decl = 38,
  sym_property_decl = 39,
  sym_type_ref = 40,
  sym_list_type = 41,
  sym_enum_type = 42,
  sym_vector_type = 43,
  sym_base_type = 44,
  sym_annotation = 45,
  sym_annotation_argument = 46,
  sym_literal = 47,
  sym_boolean = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_node_decl_repeat1 = 50,
  aux_sym_node_decl_repeat2 = 51,
  aux_sym_enum_type_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_node] = "node",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_edge] = "edge",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_enum] = "enum",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_Vector] = "Vector",
  [anon_sym_String] = "String",
  [anon_sym_Bool] = "Bool",
  [anon_sym_I32] = "I32",
  [anon_sym_I64] = "I64",
  [anon_sym_U32] = "U32",
  [anon_sym_U64] = "U64",
  [anon_sym_F32] = "F32",
  [anon_sym_F64] = "F64",
  [anon_sym_DateTime] = "DateTime",
  [anon_sym_Date] = "Date",
  [anon_sym_AT] = "@",
  [sym_type_name] = "type_name",
  [sym_enum_value] = "enum_value",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_node_decl] = "node_decl",
  [sym_edge_decl] = "edge_decl",
  [sym_property_decl] = "property_decl",
  [sym_type_ref] = "type_ref",
  [sym_list_type] = "list_type",
  [sym_enum_type] = "enum_type",
  [sym_vector_type] = "vector_type",
  [sym_base_type] = "base_type",
  [sym_annotation] = "annotation",
  [sym_annotation_argument] = "annotation_argument",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_node_decl_repeat1] = "node_decl_repeat1",
  [aux_sym_node_decl_repeat2] = "node_decl_repeat2",
  [aux_sym_enum_type_repeat1] = "enum_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_node] = anon_sym_node,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_edge] = anon_sym_edge,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_Vector] = anon_sym_Vector,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Bool] = anon_sym_Bool,
  [anon_sym_I32] = anon_sym_I32,
  [anon_sym_I64] = anon_sym_I64,
  [anon_sym_U32] = anon_sym_U32,
  [anon_sym_U64] = anon_sym_U64,
  [anon_sym_F32] = anon_sym_F32,
  [anon_sym_F64] = anon_sym_F64,
  [anon_sym_DateTime] = anon_sym_DateTime,
  [anon_sym_Date] = anon_sym_Date,
  [anon_sym_AT] = anon_sym_AT,
  [sym_type_name] = sym_type_name,
  [sym_enum_value] = sym_enum_value,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_node_decl] = sym_node_decl,
  [sym_edge_decl] = sym_edge_decl,
  [sym_property_decl] = sym_property_decl,
  [sym_type_ref] = sym_type_ref,
  [sym_list_type] = sym_list_type,
  [sym_enum_type] = sym_enum_type,
  [sym_vector_type] = sym_vector_type,
  [sym_base_type] = sym_base_type,
  [sym_annotation] = sym_annotation,
  [sym_annotation_argument] = sym_annotation_argument,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_node_decl_repeat1] = aux_sym_node_decl_repeat1,
  [aux_sym_node_decl_repeat2] = aux_sym_node_decl_repeat2,
  [aux_sym_enum_type_repeat1] = aux_sym_enum_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_node] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_edge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Vector] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_I64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DateTime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_node_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_property_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_type] = {
    .visible = true,
    .named = true,
  },
  [sym_vector_type] = {
    .visible = true,
    .named = true,
  },
  [sym_base_type] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_argument = 2,
  field_name = 3,
  field_parent = 4,
  field_source = 5,
  field_target = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_argument] = "argument",
  [field_name] = "name",
  [field_parent] = "parent",
  [field_source] = "source",
  [field_target] = "target",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 3},
  [11] = {.index = 21, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_annotation, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_annotation, 0, .inherited = true},
    {field_annotation, 1, .inherited = true},
  [4] =
    {field_annotation, 2, .inherited = true},
    {field_name, 1},
  [6] =
    {field_name, 1},
    {field_parent, 3},
  [8] =
    {field_name, 0},
    {field_type, 2},
  [10] =
    {field_name, 1},
    {field_source, 3},
    {field_target, 5},
  [13] =
    {field_annotation, 3, .inherited = true},
    {field_name, 0},
    {field_type, 2},
  [16] =
    {field_argument, 3},
    {field_name, 1},
  [18] =
    {field_annotation, 2, .inherited = true},
    {field_name, 1},
    {field_parent, 4},
  [21] =
    {field_annotation, 6, .inherited = true},
    {field_name, 1},
    {field_source, 3},
    {field_target, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 76,
  [82] = 63,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 1,
        '(', 46,
        ')', 48,
        ',', 47,
        '-', 16,
        '/', 2,
        ':', 39,
        '?', 43,
        '@', 60,
        'B', 29,
        'D', 17,
        'F', 10,
        'I', 11,
        'S', 33,
        'U', 12,
        'V', 19,
        '[', 44,
        ']', 45,
        '{', 40,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(68);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(61);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(56);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(57);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(53);
      END_STATE();
    case 15:
      if (lookahead == '4') ADVANCE(55);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_Vector);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_I32);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_I64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_U32);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_U64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_F32);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_F64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DateTime);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_Date);
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_type_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_enum_value);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'g') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_edge);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_node);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_node] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_edge] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_Vector] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [anon_sym_I32] = ACTIONS(1),
    [anon_sym_I64] = ACTIONS(1),
    [anon_sym_U32] = ACTIONS(1),
    [anon_sym_U64] = ACTIONS(1),
    [anon_sym_F32] = ACTIONS(1),
    [anon_sym_F64] = ACTIONS(1),
    [anon_sym_DateTime] = ACTIONS(1),
    [anon_sym_Date] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym_node_decl] = STATE(12),
    [sym_edge_decl] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_node] = ACTIONS(7),
    [anon_sym_edge] = ACTIONS(9),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      anon_sym_Vector,
    ACTIONS(19), 1,
      anon_sym_Date,
    STATE(17), 1,
      sym_type_ref,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(23), 4,
      sym_list_type,
      sym_enum_type,
      sym_vector_type,
      sym_base_type,
    ACTIONS(17), 9,
      anon_sym_String,
      anon_sym_Bool,
      anon_sym_I32,
      anon_sym_I64,
      anon_sym_U32,
      anon_sym_U64,
      anon_sym_F32,
      anon_sym_F64,
      anon_sym_DateTime,
  [37] = 4,
    ACTIONS(19), 1,
      anon_sym_Date,
    STATE(70), 1,
      sym_base_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 9,
      anon_sym_String,
      anon_sym_Bool,
      anon_sym_I32,
      anon_sym_I64,
      anon_sym_U32,
      anon_sym_U64,
      anon_sym_F32,
      anon_sym_F64,
      anon_sym_DateTime,
  [59] = 8,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_integer,
    STATE(63), 1,
      sym_annotation_argument,
    STATE(74), 1,
      sym_literal,
    STATE(79), 1,
      sym_boolean,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
  [87] = 8,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_integer,
    STATE(74), 1,
      sym_literal,
    STATE(79), 1,
      sym_boolean,
    STATE(82), 1,
      sym_annotation_argument,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
  [115] = 5,
    ACTIONS(31), 1,
      anon_sym_AT,
    STATE(6), 1,
      aux_sym_node_decl_repeat1,
    STATE(16), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(29), 4,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [135] = 6,
    ACTIONS(36), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      anon_sym_AT,
    STATE(9), 1,
      aux_sym_node_decl_repeat1,
    STATE(20), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [157] = 6,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(42), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      aux_sym_node_decl_repeat1,
    STATE(20), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(40), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [179] = 5,
    ACTIONS(44), 1,
      anon_sym_AT,
    STATE(9), 1,
      aux_sym_node_decl_repeat1,
    STATE(20), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(29), 4,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_LBRACE,
      anon_sym_edge,
  [199] = 5,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_node,
    ACTIONS(52), 1,
      anon_sym_edge,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 3,
      sym_node_decl,
      sym_edge_decl,
      aux_sym_source_file_repeat1,
  [218] = 3,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [233] = 5,
    ACTIONS(7), 1,
      anon_sym_node,
    ACTIONS(9), 1,
      anon_sym_edge,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 3,
      sym_node_decl,
      sym_edge_decl,
      aux_sym_source_file_repeat1,
  [252] = 3,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_LBRACE,
      anon_sym_edge,
      anon_sym_AT,
  [267] = 6,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_AT,
    STATE(6), 1,
      aux_sym_node_decl_repeat1,
    STATE(16), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [287] = 6,
    ACTIONS(67), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      aux_sym_node_decl_repeat1,
    STATE(16), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [307] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [319] = 5,
    ACTIONS(67), 1,
      anon_sym_AT,
    STATE(16), 1,
      sym_annotation,
    STATE(21), 1,
      aux_sym_node_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(75), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [337] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(77), 5,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_RBRACK,
      anon_sym_AT,
      sym_identifier,
  [349] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(79), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [361] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_LBRACE,
      anon_sym_edge,
      anon_sym_AT,
  [373] = 5,
    ACTIONS(67), 1,
      anon_sym_AT,
    STATE(6), 1,
      aux_sym_node_decl_repeat1,
    STATE(16), 1,
      sym_annotation,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [391] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_LBRACE,
      anon_sym_edge,
      anon_sym_AT,
  [403] = 3,
    ACTIONS(85), 1,
      anon_sym_QMARK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(83), 3,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [416] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(27), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [431] = 4,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [446] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(33), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [461] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [476] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [491] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [506] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(28), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [521] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [536] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [551] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [566] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(112), 4,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_AT,
      sym_identifier,
  [577] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [592] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(39), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [607] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(118), 4,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_AT,
      sym_identifier,
  [618] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(120), 4,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_AT,
      sym_identifier,
  [629] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 2,
      sym_property_decl,
      aux_sym_node_decl_repeat2,
  [644] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(124), 4,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_AT,
      sym_identifier,
  [655] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [665] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(128), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [675] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [685] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [695] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [705] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [715] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 3,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_identifier,
  [725] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [735] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [745] = 4,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [759] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [769] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [779] = 4,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [793] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [803] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(156), 3,
      ts_builtin_sym_end,
      anon_sym_node,
      anon_sym_edge,
  [813] = 4,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_enum_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [827] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [836] = 2,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [844] = 2,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [852] = 2,
    ACTIONS(167), 1,
      sym_integer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [860] = 2,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [868] = 2,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [876] = 2,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [884] = 2,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [892] = 2,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [900] = 2,
    ACTIONS(179), 1,
      sym_enum_value,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [908] = 2,
    ACTIONS(181), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [916] = 2,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [924] = 2,
    ACTIONS(185), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [932] = 2,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [940] = 2,
    ACTIONS(189), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [948] = 2,
    ACTIONS(191), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [956] = 2,
    ACTIONS(193), 1,
      sym_enum_value,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [964] = 2,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [972] = 2,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [980] = 2,
    ACTIONS(199), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [988] = 2,
    ACTIONS(201), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [996] = 2,
    ACTIONS(203), 1,
      sym_type_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1004] = 2,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1012] = 2,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1020] = 2,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1028] = 2,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1036] = 2,
    ACTIONS(213), 1,
      anon_sym_DASH_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 59,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 157,
  [SMALL_STATE(9)] = 179,
  [SMALL_STATE(10)] = 199,
  [SMALL_STATE(11)] = 218,
  [SMALL_STATE(12)] = 233,
  [SMALL_STATE(13)] = 252,
  [SMALL_STATE(14)] = 267,
  [SMALL_STATE(15)] = 287,
  [SMALL_STATE(16)] = 307,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 337,
  [SMALL_STATE(19)] = 349,
  [SMALL_STATE(20)] = 361,
  [SMALL_STATE(21)] = 373,
  [SMALL_STATE(22)] = 391,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 431,
  [SMALL_STATE(26)] = 446,
  [SMALL_STATE(27)] = 461,
  [SMALL_STATE(28)] = 476,
  [SMALL_STATE(29)] = 491,
  [SMALL_STATE(30)] = 506,
  [SMALL_STATE(31)] = 521,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 551,
  [SMALL_STATE(34)] = 566,
  [SMALL_STATE(35)] = 577,
  [SMALL_STATE(36)] = 592,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 618,
  [SMALL_STATE(39)] = 629,
  [SMALL_STATE(40)] = 644,
  [SMALL_STATE(41)] = 655,
  [SMALL_STATE(42)] = 665,
  [SMALL_STATE(43)] = 675,
  [SMALL_STATE(44)] = 685,
  [SMALL_STATE(45)] = 695,
  [SMALL_STATE(46)] = 705,
  [SMALL_STATE(47)] = 715,
  [SMALL_STATE(48)] = 725,
  [SMALL_STATE(49)] = 735,
  [SMALL_STATE(50)] = 745,
  [SMALL_STATE(51)] = 759,
  [SMALL_STATE(52)] = 769,
  [SMALL_STATE(53)] = 779,
  [SMALL_STATE(54)] = 793,
  [SMALL_STATE(55)] = 803,
  [SMALL_STATE(56)] = 813,
  [SMALL_STATE(57)] = 827,
  [SMALL_STATE(58)] = 836,
  [SMALL_STATE(59)] = 844,
  [SMALL_STATE(60)] = 852,
  [SMALL_STATE(61)] = 860,
  [SMALL_STATE(62)] = 868,
  [SMALL_STATE(63)] = 876,
  [SMALL_STATE(64)] = 884,
  [SMALL_STATE(65)] = 892,
  [SMALL_STATE(66)] = 900,
  [SMALL_STATE(67)] = 908,
  [SMALL_STATE(68)] = 916,
  [SMALL_STATE(69)] = 924,
  [SMALL_STATE(70)] = 932,
  [SMALL_STATE(71)] = 940,
  [SMALL_STATE(72)] = 948,
  [SMALL_STATE(73)] = 956,
  [SMALL_STATE(74)] = 964,
  [SMALL_STATE(75)] = 972,
  [SMALL_STATE(76)] = 980,
  [SMALL_STATE(77)] = 988,
  [SMALL_STATE(78)] = 996,
  [SMALL_STATE(79)] = 1004,
  [SMALL_STATE(80)] = 1012,
  [SMALL_STATE(81)] = 1020,
  [SMALL_STATE(82)] = 1028,
  [SMALL_STATE(83)] = 1036,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat1, 2, 0, 3),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat1, 2, 0, 3), SHIFT_REPEAT(76),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 7, 0, 11),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 6, 0, 7),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat1, 2, 0, 3), SHIFT_REPEAT(81),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat1, 1, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 3, 0, 6),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_base_type, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 5, 0, 9),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 4, 0, 8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat2, 2, 0, 0), SHIFT_REPEAT(68),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_decl_repeat2, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_type, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 4, 0, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 10, 0, 11),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 5, 0, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 6, 0, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 7, 0, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 5, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 7, 0, 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 6, 0, 5),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_decl, 8, 0, 10),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 8, 0, 7),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 9, 0, 7),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 9, 0, 11),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_argument, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nanograph_schema(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nanograph_schema",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
